### PR TITLE
Fix input data generation. Remove tailPointer + h.count line

### PR DESCRIPTION
**Pull request by dsemenovsky**
There was a difference between input data
web3swift:
```
0x3ffbd47f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000**a0**000000000000000000000000000000000000000000000000000000000000000a7465737420323334323300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d7465733233343233343233347400000000000000000000000000000000000000
```

method call from Truffle:
```
0x3ffbd47f000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000**80**000000000000000000000000000000000000000000000000000000000000000a7465737420323334323300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d7465733233343233343233347400000000000000000000000000000000000000
```
I tested and found extra increment for tailsPointer. Without the line in my latest commit it works as expected with different number of parameters.

### CODE REVIEW

**Comment by shamatar** [comment]
Hello @dsemenovsky 

I've pushed the new ABI encoder for ABIv1, would you try to run it on your data? It's also test covered now.

Sincerely, Alex

**Comment by shamatar** [comment]
@dsemenovsky 

Also if you are located in Moscow we are now looking for senior iOS developer, you can mail me if interested.

**Comment by dsemenovsky** [comment]
@shamatar I'd love to chat, but you don't have e-mail in your profile :) How do I get it?

I'll test it today and I'll let you know then

**Comment by dsemenovsky** [comment]
@shamatar You've accidentally merge link to my fork in Readme:

pod 'web3swift', git: 'https://github.com/Vaultie/web3swift.git'

I think you'd like to fix it

**Comment by shamatar** [comment]
My e-mail is public in the README file.

ABI should only miss encoding of highly nested dynamic types, like uint256[2][], although can require another rewrite with complete recursive algorithm.

Sincerely, Alex

P. S. Yes, will fix it

________________________________

**Pull request closed without merging**
